### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by henridf** [juttle/juttle-elastic-adapter#24]
i can't find this in npm... are you planning to publish this soon?

**Comment by dmehra** [comment]
Definitely, @davidgalbraith will answer when.  Meanwhile we've been doing
```
npm install juttle/elastic-adapter
```
(notice `/` instead of `-` in the package name), or simply `npm install` in the git repo clone.

**Comment by davidvgalbraith** [comment]
There's a package now! https://www.npmjs.com/package/juttle-elastic-adapter
