### ISSUE TITLE
"logstash schema"

### ISSUE THREAD

**Issue by henridf** [juttle/juttle-elastic-adapter#25]
What is the "logstash schema"? More specifically, what are the requirements for an ES "schema" to be juttle-readable?

I have a set of events that I'm storing in ES. I'd be interested to use Juttle on it, but I don't know how I need to structure the documents in order for this adapter to be able to use them.

**Comment by dmehra** [comment]
@davidvgalbraith can provide more details, but at the high level, if you ingest data into ES using logstash, and do not override the default template, the resulting set of stored events will be readable by juttle. The value of time will be located in @timestamp field in ES, but read into juttle as `time`. 

The default logstash template is mentioned [here](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-manage_template) and defined I believe [here](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json). It results in daily indices created in ES with names like `logstash-2015.01.01`. 

Here is a logstash config file that works for ES 2.1.0 with logstash 2.1.0 (assuming your data is JSON and contains a valid ISO8601 timestamp in the field `time`):

```
input {
  stdin {
    codec => "json"
  }
}
filter {
  date {
    match => ["time", "ISO8601"]
    target => "@timestamp"
  }
}
output {
  elasticsearch { hosts => localhost }
}
```

There is a known issue with the juttle adapter specifically with 2.1.0, `reduce by <fieldname>` doesn't work, requiring the user to type `reduce by '<fieldname.raw>'`, see https://github.com/juttle/juttle-elastic-adapter/issues/26

@henridf let us know if this is enough to get you started.

**Comment by henridf** [comment]
Thanks @dmehra. Actually the reason for my question is that I'm not ingesting this data using logstash. 

I was hoping to still be able to use this adapter to pull events out of my ES but it sounds the adapter is currently hard-wired to logstash. 

If/when you decide to make it more flexible, Kibana might be a good starting model: it had no issue figuring out my mapping and querying my data.

**Comment by dmehra** [comment]
Thanks @henridf, we are considering making the adapter more flexible. Mind providing a sample of the data you had, or describing its format?

**Comment by henridf** [comment]
Nothing special about the data - just a bunch of fields (including a one
containing the event timestamp).

**Comment by davidvgalbraith** [comment]
Hey! As @dmehra  noted, by "logstash schema" we mean:
- an index per day, whose name is `logstash-${day}`, e.g. `logstash-2014.09.17`
- a timestamp in the `@timestamp` field

The adapter currently supports replacing the `logstash-` in the index name with a prefix of your choosing, using `read elastic -index_prefix`. For instance `read elastic -index_prefix "events@"` will match indices named `events@2014.09.17`, `events@2015.12.28` etc.

Work is currently underway to support different time ranges per index. This would look like `read elastic -index_interval "week"` to look for indices with a one-week granularity. The options will be `day` (the default), `week`, `month`, `year`, and `none`. `none` means you'll only have one index, fully specified by your `index_prefix`.

Finally, we'll add a `-timeField` option, so if you don't use `@timestamp` the adapter will read your data with `read elastic -timeField "my_time_field"`.

Please let me know if all the above will enable you to use the adapter, thanks!

**Comment by henridf** [comment]
Yes, the above will enable me to use the adapter. I'll be using the `none`
index interval. Thanks!

**Comment by henridf** [comment]
one more thing  re `timeField` - please also support it in `write` (where it's currently hard-coded to `time`)

**Comment by dmehra** [comment]
The work for this is in PR #30 (incl. documented schema) and #35.

**Comment by demmer** [comment]
I'm just catching up from the holidays and reviewing these changes to support `-index_prefix` and `-index_interval`... Notwithstanding the fact that I think we should use camelCase as mentioned in #35, I think there's an opportunity to tighten things up and make it easier to use.

Specifically, what if we make the two options `-index` and `-indexInterval`. We would require `-index` to be specified, but `-indexInterval` would default to null, however if specified, then `-index` must end in a "*".

Thus to replicate the current default for the "logstash schema" the user would do:

`read elastic -index 'logstash@*' -indexInterval 'day'`

To read from a single index the user would do:

`read elastic -index 'tweets'`

To read from multiple indices but without any fancy logic to select a subset of them based on the time range of the query, the user could do:

`read elastic -index 'logstash@*'`
