### ISSUE TITLE
Timechart won't render when fed by `read elastic`

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-elastic-adapter#28]
I'm filing this as an elastic adapter bug, because the same code when reading from a file produces a timechart with no issue.

This works:
```
read file -file '/tmp/data_sorted_lines.json' -format 'jsonl' -timeField 'created_at'
| reduce -every :day: count()
| (
  view timechart;
  head 10 | view table
)
```

![image](https://cloud.githubusercontent.com/assets/5817365/12047189/4252e7bc-ae7c-11e5-9ca6-90e3f13cae29.png)

This doesn't work - the timechart has no line and the time period is set to "a few seconds from NaN to NaN":
```
read elastic -from :2015-01-01: -to :2015-07-02:
| reduce -every :day: count()
| (
  view timechart;
  head 10 | view table
)
```

![image](https://cloud.githubusercontent.com/assets/5817365/12047194/52661a16-ae7c-11e5-948b-1b84a99f194c.png)

Adding `view timechart -duration :6 months:` (or 12 months) made no difference, still "NaN" time period. Adding duration to the first program makes a difference, for example with "12 months" I see the series line for first 6 months, then nothing for later 6 months, as expected since they have no data. So, the behavior of timechart view appears correct, making me think it's the read from elastic that fails to pass something expected to the sink.

The data in ES is exactly the same as the data in the file (in fact it was ingested into ES by `read file | write elastic`), and you can see in the above screenshots that the table data is identical.

**Comment by dmehra** [comment]
@davidgalbraith this is a new blocker for the tutorial, https://github.com/juttle/juttle/pull/15, would appreciate a look.

**Comment by dmehra** [comment]
Attaching the data file, zipped because Github doesn't accept .json attachments (whyever not?!) and it's on the big side, 27MB raw. A small subset would reproduce the bug too.
 
[data_sorted_lines.zip](https://github.com/juttle/juttle-elastic-adapter/files/76455/data_sorted_lines.zip)

**Comment by davidvgalbraith** [comment]
This is a timechart bug. It doesn't format `from` and `to` options appropriately. `read file` works because it doesn't have `from` and `to` options. @go-oleg is working on it.

**Comment by davidvgalbraith** [comment]
This was fixed by https://github.com/juttle/outrigger/pull/25.
