### ISSUE TITLE
Result window is too large

### ISSUE THREAD

**Issue by davidvgalbraith** [juttle/juttle-elastic-adapter#51]
If you read from a dataset with more than 10,000 simultaneous points, it'll fail with `Result window is too large, from + size must be less than or equal to: [10000] but was [20000].` It shouldn't do that.

**Comment by demmer** [comment]
IIRC this is a new default setting in ES 2.0.

It seems most sensible to change the juttle default to only read 10,000 points at a time by default instead of 20,000 points at a time.

**Comment by davidvgalbraith** [comment]
It does only read 10,000 points at a time by default. But if there's 10,000 simultaneous points we do the "bridge fetch" which goes for another 10,000. I fixed this way back in https://github.com/juttle/juttle-elastic-adapter/pull/10 but that didn't end up getting reviewed before https://github.com/juttle/juttle-elastic-adapter/pull/14 in which I totally rewrote everything.

**Comment by demmer** [comment]
Ah I see. OK cool.
