### ISSUE TITLE
In the absence of `-type` read does not default to all types

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-elastic-adapter#67]
If my data has document type, and I explicitly specify `-type 'tag1,tag2'` in the read, I get data of those types. However if I omit `-type` option, my read returns nothing. This does not match the documentation in the README that says we default to "all types". This is the behavior with ES 1.5.2 and AWS Elastic (didn't test with 2.1.1).

I have a feeling this behavior started with juttle-elastic-adapter 0.3.1 that uses the newer aws4 via our aws-es... pretty sure it was defaulting to read all types earlier today before 0.3.1 came to be.

**Comment by davidvgalbraith** [comment]
@dmehra can you repro this with 0.4? I can't. Thinking it was actually https://github.com/juttle/juttle-elastic-adapter/issues/66 or https://github.com/juttle/juttle-elastic-adapter/issues/62.

**Comment by dmehra** [comment]
Yes, reproducing right now.
