### ISSUE TITLE
Unit tests to add

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-elastic-adapter#88]
Review of existing unit tests in this adapter, assisted by looking at the code coverage, revealed a few gaps we should fill in. 

### Filtering

The big gap is missing filtering tests for most of [filter-es-compiler.js](https://github.com/juttle/juttle-elastic-adapter/blob/master/lib/filter-es-compiler.js)
- incl. AND, OR, NOT expressions
- incl. =, !=, ~=, <, >, <=, >=
- incl. strings and numbers and time fields and booleans
I manually stepped through a variety of cases and believe there aren't any bugs, but we need the test coverage to make sure none will sneak in.

### Optimizations

[doesn't optimize over prior head optimization](https://github.com/juttle/juttle-elastic-adapter/blob/master/test/optimization.spec.js#L167)
- [x] would be a better test if it did `tail 1` rather than `tail 0`

[optimizes count](https://github.com/juttle/juttle-elastic-adapter/blob/master/test/optimization.spec.js#L177)
- [x] add: testcase for optimizing `count(name)`, `count(name) by type`, `reduce -every count(name)`

covered reducers are: count(), sum(bytes), avg(bytes), max(bytes), min(bytes), count_unique(bytes)
what about the rest?
- [x] delta
- [x] first
- [x] last
- [x] mad
- [x] percentile
- [x] sigma

do these procs get optimized:
- [x] sort
- [x] uniq
- [x] keep (there’s [juttle issue on this](https://github.com/juttle/juttle/issues/221))
- [x] filter (could we optimize? when it’s equivalent to read filter expression?)

### Live

[live.spec.js](https://github.com/juttle/juttle-elastic-adapter/blob/master/test/live.spec.js) - does live really work?
- [x] if so, add: live read with filter expression
- [ ] (if we can) live read that crosses index interval boundary

### Miscellaneous

https://github.com/juttle/juttle-elastic-adapter/blob/master/test/index-intervals.spec.js#L12
this does negative tests for * in the middle of index , what about spaces, are they ok? other symbols?

[compiles moments in filter expressions](https://github.com/juttle/juttle-elastic-adapter/blob/master/test/elastic-adapter.spec.js#L117)
- [x] add: positive test for ‘other_time = :5 minutes ago:’ and ‘some_interval = :5 minutes:’

[writes a point with a giant field](https://github.com/juttle/juttle-elastic-adapter/blob/master/test/elastic-adapter.spec.js#L141)
- [x] do we need a matching test to read, or is that covered by verify_import?

same for [writes a point with an array and object field](https://github.com/juttle/juttle-elastic-adapter/blob/master/test/elastic-adapter.spec.js#L159)
- [x] can we read them back? can we filter on them? can we reduce by them?

[errors if you write a point without time](https://github.com/juttle/juttle-elastic-adapter/blob/master/test/elastic-adapter.spec.js#L172)
- [x] in tests like this, it’s prudent to check that after getting back the error, you still have the same count of points in ES as before (i.e.: we didn’t report error but still write some garbage into it)

- [x] add testcase for writing and reading points that span index intervals, i didn't see that covered

- [x] add testcase for reading over time interval where some, but not all indices have points

[reads and writes with a configured default type](https://github.com/juttle/juttle-elastic-adapter/blob/master/test/elastic-adapter.spec.js#L287)
- [x] question on this, as the testcase code confuses me, is it still using ‘aws’ as type? that seems overloaded as we have `-type`

- [x] check: can you read more than one -type by listing them out, or does last option win?

- [x] add testcase for reading no points if supplied -type isn’t in the data, should return empty result without error (but maybe with warning? not sure.)

[endpoints](https://github.com/juttle/juttle-elastic-adapter/blob/master/test/elastic-adapter.spec.js#L313)
- [x] add: endpoints test that supplies more than one -id - does last one win?

same for
[-index argument](https://github.com/juttle/juttle-elastic-adapter/blob/master/test/elastic-adapter.spec.js#L337)
- [x] with multiple `-index`, does last one win? or does it work to read multiple indices? what about write?

[reads and writes with -idField "_id"](https://github.com/juttle/juttle-elastic-adapter/blob/master/test/elastic-adapter.spec.js#L456)
- [x] add test that filters `read elastic -idField ‘my-id’ my-id = ’42’, for id value being number or string (ES has only numbers in their examples, but strings should work)

**Comment by davidvgalbraith** [comment]
```
covered reducers are: count(), sum(bytes), avg(bytes), max(bytes), min(bytes), count_unique(bytes)
what about the rest?
```
The rest don't get optimized.
```
do these procs get optimized:
```
Nope!
```
writes a point with a giant field

    do we need a matching test to read, or is that covered by verify_import?

```
We can't write such points anymore, so there's no need to test reading them.

**Comment by dmehra** [comment]
Let's add a new test in the limits.spec.js that writes and reads a big field that's not too big, i.e. max allowed value size.

**Comment by davidvgalbraith** [comment]
The `does last option win?` questions belong in tests of the Juttle compiler. Currently the last option wins although I could see a case for making that a validation error.

**Comment by dmajda** [comment]
> Currently the last option wins although I could see a case for making that a validation error.

[Me too.](juttle/juttle#401)
