### ISSUE TITLE
Don't write to indices / document types that don't exist

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-elastic-adapter#90]
This is a sister issue to #89, both in service of the same goal: steer the user away from writing analyzed string fields to ES, because that won't result in good behavior when reading back through juttle (specifically, `name=value` filter and `reduce by` will not do what you'd want them to do). 

If the user set up the mapping in ES explicitly when creating their index and document type, we will trust them to know what they're doing. However, when using `write elastic`, they may assume that we are choosing the "right" setup. We do that for the default `juttle` index in #89, but if the user names a different index / doc type, we only have two choices:

1. if the index / doc type combination already exists, it must have been set up by the user explicitly as they desired, and we will proceed to write to it;
2. if the index / doc type combo does not exist, we should refuse to write, rather than going ahead with the write and getting the default all-strings-as-analyzed ES mapping.

That's what this issue is for: let's fail to write if the named index / type does not already exist. (For interval-based indices, it means that not a single instance of the index exists.)

**Comment by dmehra** [comment]
@philrz please validate that this is where our discussion landed.

**Comment by davidvgalbraith** [comment]
So, I thought about this more in light of the "we want to be able to write a new daily index even if it doesn't already exist" thing. The only way to do that is to check for an index with the same `prefix` and take its mapping and put it into the new index. That's pretty invasive already, so I figure let's just go all the way and have any index created by the adapter be non-analyzed.

**Comment by dmehra** [comment]
I'm good with that. In that case, #89 will be covered by this issue, as the juttle index will simply be a case of creating an index, and we'd set non_analyzed on it.

**Comment by davidvgalbraith** [comment]
I amended https://github.com/juttle/juttle-elastic-adapter/issues/89 with the new plan. Let's close this one.
